name: CI/CD - Build, Push, and Update Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REPOSITORY: cpmodule2025
  AWS_REGION: eu-central-1
  LAMBDA_FUNCTION_NAME: cpmodule2025-website 

jobs:
  build-push-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Baue das Image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
          # Pushe das Image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest